### PR TITLE
Add TabbyML to list

### PR DESCRIPTION
**Pull request by wsxiaoys**

### CODE REVIEW

**Review by beyang — CHANGES_REQUESTED** [review]
[Landing page current](https://tabbyml.com/) currently 404s, mind resubmitting after it's up?

**Comment by wsxiaoys** [comment]
Seems that there was an outage on DNS - PTAL?

**Comment by jdorfman** [comment]
@wsxiaoys is this your project? If so when will it be available for anyone to sign up?

**Comment by wsxiaoys** [comment]
> @wsxiaoys is this your project? If so when will it be available for anyone to sign up?

Yes! I'm working heavilly on it to make it ready for a public release, hopefully in early Apr!

**Comment by jdorfman** [comment]
@wsxiaoys cool well make a new PR when it is live. We want to keep the list with awesome tools devs can use today (no waitlist).  Thanks :)

**Pull request closed without merging**
